# Generated by Django 5.1.7 on 2025-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productitem_rename_features_product_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='target_markets',
        ),
        migrations.AddField(
            model_name='solution',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
