# Generated by Django 5.1.7 on 2025-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_abouthero_companyoverview_missionvision_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Partner Descriptions',
            },
        ),
    ]
