# Generated by Django 4.2.2 on 2025-04-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceMode', models.BooleanField(default=False)),
                ('maintenanceMessage', models.TextField(blank=True, default='Site is currently under maintenance. Please check back later.', null=True)),
                ('siteName', models.CharField(blank=True, default='MK Digital Security Solutions', max_length=255, null=True)),
                ('siteDescription', models.CharField(blank=True, default='Digital Security for a Connected World', max_length=255, null=True)),
                ('contactEmail', models.EmailField(blank=True, default='contact@example.com', max_length=254, null=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
