# Generated by Django 4.2.2 on 2025-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_newsdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allowedIPs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enableCaptcha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enableTwoFactorAuth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maxLoginAttempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='passwordPolicyExpiryDays',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='passwordPolicyMinLength',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='passwordPolicyRequireLowercase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='passwordPolicyRequireNumbers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='passwordPolicyRequireSpecialChars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='passwordPolicyRequireUppercase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sessionTimeout',
            field=models.IntegerField(default=30),
        ),
    ]
