# Generated by Django 4.2.2 on 2025-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitesettings_allowedips_sitesettings_enablecaptcha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyrightText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footerLinks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footerText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logoAlt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logoHeight',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logoWidth',
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='showSocialLinks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='socialLinks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
