# Generated by Django 4.2.2 on 2025-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_description_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/hero/'),
        ),
    ]
