# Generated by Django 4.2.2 on 2025-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_productdescription_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
