# Generated by Django 4.2.2 on 2025-05-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_productdescription_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutiondescription',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/hero/'),
        ),
    ]
