# Generated by Django 4.2.2 on 2025-05-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_solutiondescription_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutiondescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutiondescription',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
