# Generated by Django 4.2.2 on 2025-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_solutiondescription_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthero',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/hero/'),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
