# Generated by Django 4.2.2 on 2025-05-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_background_image_to_contactdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdescription',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/hero/'),
        ),
        migrations.AlterField(
            model_name='newsdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsdescription',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
