# Generated by Django 4.2.2 on 2025-05-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_newsdescription_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/hero/'),
        ),
    ]
